import cjsImport from "./index.js";

const {
	HeroReplay,
	DetachedElement,
	Command,
	ConnectionToHeroCore,
	InteractionCommand,
	MouseButton,
	IResourceType,
	ResourceType,
	KeyboardKey,
	BlockedResourceType,
	Node,
	FrameEnvironment,
	Tab,
	Resource,
	WebsocketResource,
	XPathResult,
	LocationStatus,
	LocationTrigger,
	IHeroCreateOptions,
	IHeroReplayCreateOptions,
	IConnectionToCoreOptions,
	ISuperElement,
	ISuperNode,
	ISuperHTMLElement,
	ISuperNodeList,
	ISuperHTMLCollection,
	ISuperStyleSheet,
	ISuperDocument,
	ISuperText,
	IUserProfile,
	IElement,
	INode,
	IHTMLElement,
	INodeList,
	IHTMLCollection,
} = cjsImport;

export {
	BlockedResourceType,
	Command,
	ConnectionToHeroCore,
	DetachedElement,
	FrameEnvironment,
	HeroReplay,
	IConnectionToCoreOptions,
	IElement,
	IHeroCreateOptions,
	IHeroReplayCreateOptions,
	IHTMLCollection,
	IHTMLElement,
	INode,
	INodeList,
	InteractionCommand,
	IResourceType,
	ISuperDocument,
	ISuperElement,
	ISuperHTMLCollection,
	ISuperHTMLElement,
	ISuperNode,
	ISuperNodeList,
	ISuperStyleSheet,
	ISuperText,
	IUserProfile,
	KeyboardKey,
	LocationStatus,
	LocationTrigger,
	MouseButton,
	Node,
	Resource,
	ResourceType,
	Tab,
	WebsocketResource,
	XPathResult,
};

export default cjsImport.default;
